import { lib, game, ui, get, ai, _status } from "../../noname.js";

const characters = {
    "yuma": {
        sex: "female",
        group: "yuan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["zhijian", "guzheng", "wangxi"],
        img: "extension/魔法纪录/image/yuma.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/yuma.mp3"],
    },
    "kirika": {
        sex: "female",
        group: "yuan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["kirika_shensu", "ganglie", "shebian"],
        img: "extension/魔法纪录/image/kirika.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/kirika.mp3"],
    },
    "oriko": {
        sex: "female",
        group: "yuan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["oriko_yuzhi", "oriko_jiangsha", "weimu", "oriko_xianzhong"],
        img: "extension/魔法纪录/image/oriko.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/oriko.mp3"],
        isZhugong: true
    },
    "ashley": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["ashley_yuanyu", "ashley_mengshu"],
        img: "extension/魔法纪录/image/ashley.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/ashley.mp3"],
    },
    "riko": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["dcduliang", "tunchu", "shuliang"],
        img: "extension/魔法纪录/image/riko.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/riko.mp3"],
    },
    "rika": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["rika_sanshe", "reguose", "rika_liuge"],
        img: "extension/魔法纪录/image/rika.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/rika.mp3"],
    },
    "tsuruno": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["tsuruno_qiangyun", "tsuruno_jizhi"],
        img: "extension/魔法纪录/image/tsuruno.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/tsuruno.mp3"],
    },
    "sana": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["sana_touming", "xinjushou", "xinjiewei"],
        img: "extension/魔法纪录/image/sana.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/sana.mp3"],
    },
    "iroha": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["olhaoshi", "iroha_dimeng", "dckrmingshi", "iroha_yuanjiu"],
        img: "extension/魔法纪录/image/iroha.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/iroha.mp3"],
        isZhugong: true,
    },
    "yachiyo": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["rexingshang", "fangzhu", "sbwushuang", "yachiyo_gujun"],
        img: "extension/魔法纪录/image/yachiyo.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/yachiyo.mp3"],
        isZhugong: true
    },
    "felicia": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["repojun", "reyicong"],
        img: "extension/魔法纪录/image/felicia.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/felicia.mp3"],
    },
    "toka": {
        sex: "female",
        group: "ma",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["xinleiji", "xinguidao", "magius_jiefang"],
        img: "extension/魔法纪录/image/toka.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/toka.mp3"],
        isZhugong: true
    },
    "alina": {
        sex: "female",
        group: "ma",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["alina_moying", "juanhui"],
        img: "extension/魔法纪录/image/alina.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/alina.mp3"],
    },
    "lena": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["lena_huashen", "lena_xinsheng"],
        img: "extension/魔法纪录/image/lena.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/lena.mp3"],
    },
    "kaede": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["kaede_manmiao", "kaede_buyi", "dczhuiyi"],
        img: "extension/魔法纪录/image/kaede.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/kaede.mp3"],
    },
    "momoko": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["momoko_qiangxi", "buqu"],
        img: "extension/魔法纪录/image/momoko.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/momoko.mp3"],
    },
    "asuka": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["asuka_kurou", "asuka_longzhen"],
        img: "extension/魔法纪录/image/asuka.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/asuka.mp3"],
    },
    "yueye": {
        sex: "female",
        group: "ma",
        hp: 5,
        maxHp: 5,
        hujia: 0,
        skills: ["yueye_yingyin"],
        img: "extension/魔法纪录/image/yueye.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/yueye.mp3"],
    },
    "yuexiao": {
        sex: "female",
        group: "ma",
        hp: 5,
        maxHp: 5,
        hujia: 0,
        skills: ["yuexiao_yingyu"],
        img: "extension/魔法纪录/image/yuexiao.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/yuexiao.mp3"],
    },
    "madoka": {
        sex: "female",
        group: "yuan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["madoka_liegong", "madoka_yingbian", "madoka_xieli"],
        img: "extension/魔法纪录/image/madoka.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/madoka.mp3"],
        isZhugong: true
    },
    "homura": {
        sex: "female",
        group: "yuan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["reguanxing", "homura_juwu", "homura_shiting"],
        img: "extension/魔法纪录/image/homura.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/homura.mp3"],
    },
    "homura2": {
        sex: "female",
        group: "yuan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["homura2_jihuo", "ollianhuan", "huoji"],
        img: "extension/魔法纪录/image/homura2.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/homura2.mp3"],
    },
    "nanaka": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["nanaka_huaxin", "rejizhi"],
        img: "extension/魔法纪录/image/nanaka.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/nanaka.mp3"],
    },
    "hazuki": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["huituo", "hazuki_mingjian"],
        img: "extension/魔法纪录/image/hazuki.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/hazuki.mp3"],
    },
    "karin": {
        sex: "female",
        group: "ma",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["daoshu", "weicheng"],
        img: "extension/魔法纪录/image/karin.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/karin.mp3"],
    },
    "nemu": {
        sex: "female",
        group: "ma",
        hp: 5,
        maxHp: 5,
        hujia: 0,
        skills: ["nemu_zhiyao", "nemu_sanyao", "nemu_tiruo"],
        img: "extension/魔法纪录/image/nemu.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/nemu.mp3"],
    },
    "mami": {
        sex: "female",
        group: "yuan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["reyingzi", "mami_duanbian", "mami_tiro_finale"],
        img: "extension/魔法纪录/image/mami.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/mami.mp3"],
    },
    "kyoko": {
        sex: "female",
        group: "yuan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["oltuntian", "jixi", "reguhuo"],
        img: "extension/魔法纪录/image/kyoko.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/kyoko.mp3"],
    },
    "mabayu": {
        sex: "female",
        group: "yuan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["nzry_chenglve", "nzry_cunmu", "nzry_shicai", "mabayu_jingxiang"],
        img: "extension/魔法纪录/image/mabayu.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/mabayu.mp3"],
        isZhugong: true
    },
    "ren": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["xinwuyan", "ren_beige", "duanchang"],
        img: "extension/魔法纪录/image/ren.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/ren.mp3"],
    },
    "ulti_madoka": {
        sex: "female",
        group: "yuan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["madoka_dengshen", "twshelie", "sbliegong", "madoka_xieli"],
        img: "extension/魔法纪录/image/ulti_madoka.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/ulti_madoka.mp3"],
        isZhugong: true,
        isAiForbidden: true,
    },
    "sayaka": {
        sex: "female",
        group: "yuan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["xinkuanggu", "gzyinghun", "sayaka_qiangyin"],
        img: "extension/魔法纪录/image/sayaka.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/sayaka.mp3"],
    },
    "Kagome": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["hsdianmo", "hszaibi"],
        img: "extension/魔法纪录/image/Kagome.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/Kagome.mp3"]
    },
    "mifuyu": {
        sex: "female",
        group: "ma",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["dcwumei", "dczhanmeng"],
        img: "extension/魔法纪录/image/mifuyu.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/mifuyu.mp3"],
    },
    "meru": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["zhiming", "twxingbu"],
        img: "extension/魔法纪录/image/meru.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/meru.mp3"]
    },
    "kazumi": {
        sex: "female",
        group: "wan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["qixing", "kuangfeng", "dawu", "kazumi_xingyun"],
        img: "extension/魔法纪录/image/kazumi.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/kazumi.mp3"],
        isZhugong: true
    },
    "kushu": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["jiushi", "keji", "refankui"],
        img: "extension/魔法纪录/image/kushu.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/kushu.mp3"],
    },
    "kokoro": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["jieyue", "yizhong"],
        img: "extension/魔法纪录/image/kokoro.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/kokoro.mp3"],
    },
    "ayame": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["tianyi", "hanzhan"],
        img: "extension/魔法纪录/image/ayame.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/ayame.mp3"],
    },
    "hanna": {
        sex: "female",
        group: "ye",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["xinjuece", "dcmieji", "dcfencheng", "reluanwu"],
        img: "extension/魔法纪录/image/hanna.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/hanna.mp3"],
    },
    "kuroe": {
        sex: "female",
        group: "ma",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["qingbei", "dcsuishi"],
        img: "extension/魔法纪录/image/kuroe.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/kuroe.mp3"],
    },
    "dp_iroha": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["ani_lieying", "jueqing", "shangshi", "dckrmingshi"],
        img: "extension/魔法纪录/image/dp_iroha.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/dp_iroha.mp3"],
    },
    "kanae": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["kaikang", "mashu"],
        img: "extension/魔法纪录/image/kanae.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/kanae.mp3"]
    },
    "name": {
        sex: "female",
        group: "yuan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["name_dengtai"],
        img: "extension/魔法纪录/image/name.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/name.mp3"]
    },
    "mitama": {
        sex: "female",
        group: "wan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["gongxiu", "jinghe", "ns_chuanshu"],
        img: "extension/魔法纪录/image/mitama.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/mitama.mp3"],
    },
    "ui": {
        sex: "female",
        group: "ma",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["ui_jinghua", "ui_wangyou", "dckrmingshi"],
        img: "extension/魔法纪录/image/ui.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/ui.mp3"],
    },
    "nagisa": {
        sex: "female",
        group: "yuan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["tiandu", "new_reqingnang", "olniepan"],
        img: "extension/魔法纪录/image/nagisa.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/nagisa.mp3"]
    },
    "kanagi": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["reshuishi", "kanagi_duxin", "kanagi_nvpu", "kanagi_dongyou"],
        img: "extension/魔法纪录/image/kanagi.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/kanagi.mp3"],
        isZhugong: true
    },
    "suzune": {
        sex: "female",
        group: "wan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["retuogu", "shanzhuan"],
        img: "extension/魔法纪录/image/suzune.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/suzune.mp3"]
    },
    "dArc": {
        sex: "female",
        group: "wan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["retieji", "nanaka_huaxin", "gongji"],
        img: "extension/魔法纪录/image/dArc.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/dArc.mp3"]
    },
    "himika": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["dclihuo", "olchunlao"],
        img: "extension/魔法纪录/image/himika.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/himika.mp3"],
    },
    "masara": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["rebiyue", "masara_cisha", "qiluan"],
        img: "extension/魔法纪录/image/masara.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/masara.mp3"],
    },
    "seika": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["seika_huzhu"],
        img: "extension/魔法纪录/image/seika.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/seika.mp3"],
    },
    "rera": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["xinfu_jijie", "rera_nuanxin"],
        img: "extension/魔法纪录/image/rera.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/rera.mp3"],
    },
    "mito": {
        sex: "female",
        group: "huan",
        hp: 5,
        maxHp: 5,
        hujia: 0,
        skills: ["dcsbkuangzhan", "hanzhan"],
        img: "extension/魔法纪录/image/mito.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/mito.mp3"],
    },
    "ryo": {
        sex: "female",
        group: "ma",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["ryo_yaozuo", "dcsbzhuanwen"],
        img: "extension/魔法纪录/image/ryo.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/ryo.mp3"]
    },
    "ai": {
        sex: "female",
        group: "ma",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["xingtu", "scls_juezhi", "ai_shuxin"],
        img: "extension/魔法纪录/image/ai.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/ai.mp3"],
    },
    "asumi": {
        sex: "female",
        group: "yuan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["asumi_zhuilie", "asumi_yinhu"],
        img: "extension/魔法纪录/image/asumi.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/asumi.mp3"],
    },
    "saint_mami": {
        sex: "female",
        group: "ma",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["reyingzi", "saint_mami_tiro_finale", "starxiaoyan", "starjiaowang"],
        img: "extension/魔法纪录/image/saint_mami.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/saint_mami.mp3"],
    },
    "uwasa_tsuruno": {
        sex: "female",
        group: "ma",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["tsuruno_qiangyun", "drlt_jueyan", "tsuruno_tuanluan"],
        img: "extension/魔法纪录/image/uwasa_tsuruno.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/uwasa_tsuruno.mp3"],
    },
    "devil_homura": {
        sex: "female",
        group: "yuan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["dcgeyuan", "dcgusuan", "dcjieshu", "bazhen"],
        img: "extension/魔法纪录/image/devil_homura.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/devil_homura.mp3"],
        isAiForbidden: true,
    },
    "hinano": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["hinano_huawu", "hinano_duji", "hinano_shiyao", "hinano_baoming"],
        img: "extension/魔法纪录/image/hinano.png",
        dieAudios: ["ext:魔法纪录/audio/die/hinano.mp3"],
    },
    "yuna": {
        isZhugong: true,
        sex: "female",
        group: "wan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["yuna_chouhai", "yuna_xuehen", "yuna_liuli", "yuna_xuemeng"],
        img: "extension/魔法纪录/image/yuna.png",
        dieAudios: ["ext:魔法纪录/audio/die/yuna.mp3"],
    },
    "shigure": {
        sex: "female",
        group: "ma",
        hp: 5,
        maxHp: 5,
        hujia: 0,
        skills: ["olkanpo", "ollongdan"],
        img: "extension/魔法纪录/image/shigure.png",
        dieAudios: ["ext:魔法纪录/audio/die/shigure.mp3"],
    },
    "hagumu": {
        sex: "female",
        group: "ma",
        hp: 5,
        maxHp: 5,
        hujia: 0,
        skills: ["new_rewusheng", "oltiaoxin"],
        img: "extension/魔法纪录/image/hagumu.png",
        dieAudios: ["ext:魔法纪录/audio/die/hagumu.mp3"],
    },
    "shizuka": {
        sex: "female",
        group: "wan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["shizuka_xueji", "komari_xueshang"],
        img: "extension/魔法纪录/image/shizuka.png",
        dieAudios: ["ext:魔法纪录/audio/die/shizuka.mp3"],
    },
    "himena": {
        isZhugong: true,
        sex: "female",
        group: "ma",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["himena_zhiquan", "himena_shanji", "magius_zhishang"],
        img: "extension/魔法纪录/image/himena.png",
        dieAudios: ["ext:魔法纪录/audio/die/himena.mp3"],
    },
    "nayuta": {
        sex: "female",
        group: "wan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["nayuta_kanwu", "nayuta_mingsu", "olhongyuan"],
        img: "extension/魔法纪录/image/nayuta.png",
        dieAudios: ["ext:魔法纪录/audio/die/nayuta.mp3"],
    },
    "mikage": {
        sex: "female",
        group: "wan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["mikage_yuying", "mikage_yingbing"],
        img: "extension/魔法纪录/image/mikage.png",
        dieAudios: ["ext:魔法纪录/audio/die/mikage.mp3"],
    },
    "sakura": {
        sex: "female",
        group: "ma",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["tiandu", "sakura_yinghu", "sakura_yingmeng"],
        img: "extension/魔法纪录/image/sakura.png",
        dieAudios: ["ext:魔法纪录/audio/die/sakura.mp3"],
    },
    "juri": {
        sex: "female",
        group: "wan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["juri_fenyan", "juri_longhuo"],
        img: "extension/魔法纪录/image/juri.png",
        dieAudios: ["ext:魔法纪录/audio/die/juri.mp3"],
    }
}

const character_translates = {
    "ulti_madoka_prefix": "神",
    "魔法纪录": "魔法纪录",
    yuma: "千岁由麻",
    kirika: "吴纪里香",
    oriko: "美国织莉子",
    ashley: "阿什莉·泰勒",
    riko: "千秋理子",
    rika: "绫野梨花",
    tsuruno: "由比鹤乃",
    sana: "二叶莎奈",
    iroha: "环彩羽",
    yachiyo: "七海八千代",
    felicia: "深月菲莉西亚",
    toka: "里见灯花",
    alina: "阿莉娜·格雷",
    lena: "水波玲奈",
    kaede: "秋野枫",
    momoko: "十咎桃子",
    asuka: "龙城明日香",
    yueye: "天音月夜",
    yuexiao: "天音月咲",
    madoka: "鹿目圆",
    homura: "晓美焰",
    "homura2": "麻花焰",
    nanaka: "常盘七香",
    hazuki: "游佐叶月",
    karin: "御园花凛",
    nemu: "柊音梦",
    mami: "巴麻美",
    kyoko: "佐仓杏子",
    mabayu: "爱生眩",
    ren: "五十铃怜",
    "ulti_madoka": "神鹿目圆",
    sayaka: "美树沙耶香",
    Kagome: "佐鸟笼目",
    mifuyu: "梓美冬",
    meru: "安名梅露",
    kazumi: "和美",
    kushu: "入名库什",
    kokoro: "粟根心",
    ayame: "三栗菖蒲",
    hanna: "更纱帆奈",
    kuroe: "黑江",
    "dp_iroha": "DP环彩羽",
    "dp_iroha_prefix": "DP",
    kanae: "雪野加奈惠",
    name: "小名",
    mitama: "八云御魂",
    ui: "环忧",
    nagisa: "百江渚",
    kanagi: "和泉十七夜",
    suzune: "天乃铃音",
    dArc: "贞德",
    himika: "真尾日美香",
    masara: "加贺见真良",
    seika: "桑水清佳",
    rera: "伊吹丽良",
    mito: "相野未都",
    ryo: "观鸟令",
    ai: "爱酱",
    asumi: "神名浅海",
    "saint_mami": "圣巴麻美",
    "saint_mami_prefix": "圣",
    "uwasa_tsuruno": "谣由比鹤乃",
    "uwasa_tsuruno_prefix": "谣",
    "devil_homura": "魔晓美焰",
    "devil_homura_prefix": "魔",
    hinano: "都雏乃",
    yuna: "红晴结菜",
    shigure: "宫尾时雨",
    hagumu: "安积育梦",
    shizuka: "时女静香",
    himena: "蓝家姬奈",
    nayuta: "里见那由他",
    mikage: "八云御影",
    sakura: "柊樱子",
    juri: "大庭树里",
}

const perfectPairs = {
    oriko: ["kirika"],
    kirika: ["oriko"],
    madoka: ["homura", "mami", "sayaka", "homura2", "ulti_madoka", "devil_homura"],
    "ulti_madoka": ["sayaka", "homura", "madoka", "devil_homura"],
    homura: ["madoka", "homura2", "ulti_madoka", "kyoko", "mabayu", "devil_homura"],
    "homura2": ["madoka", "mami", "sayaka", "homura", "devil_homura"],
    "devil_homura": ["homura", "homura2", "ulti_madoka", "madoka"],
    mami: ["kyoko", "mabayu", "homura2", "madoka", "sayaka", "nagisa"],
    kyoko: ["mami", "homura", "homura2", "sayaka", "yuma"],
    sayaka: ["madoka", "kyoko", "homura2", "mami"],
    yuma: ["kyoko"],
    mabayu: ["mami", "homura", "homura2"],
    iroha: ["yachiyo", "felicia", "sana", "kuroe", "ui", "dp_iroha"],
    dp_iroha: ["iroha"],
    yachiyo: ["iroha", "tsuruno", "momoko", "mifuyu", "meru", "kanae"],
    felicia: ["iroha", "tsuruno"],
    tsuruno: ["felicia", "yachiyo"],
    sana: ["iroha"],
    momoko: ["yachiyo", "kaede", "lena", "mitama"],
    lena: ["momoko", "kaede"],
    kaede: ["momoko", "lena"],
    toka: ["alina", "nemu", "ui", "nayuta", "sakura"],
    alina: ["toka", "nemu", "karin"],
    nemu: ["alina", "toka", "ui", "ai", "sakura"],
    karin: ["alina"],
    nanaka: ["hazuki"],
    hazuki: ["nanaka"],
    yueye: ["yuexiao", "mifuyu"],
    yuexiao: ["yueye"],
    ashley: ["riko"],
    riko: ["ashley"],
    rika: ["ren"],
    ren: ["rika"],
    mifuyu: ["yachiyo", "toka", "yueye"],
    meru: ["yachiyo"],
    kuroe: ["iroha"],
    kanae: ["yachiyo"],
    mitama: ["momoko", "mikage"],
    nagisa: ["mami"],
    ui: ["toka", "nemu", "iroha", "sakura"],
    ai: ["nemu"],
    kokoro: ["masara"],
    masara: ["kokoro"],
    mito: ["seika", "rera"],
    seika: ["mito", "rera"],
    rera: ["seika", "mito"],
    hagumu: ["shigure", "himena"],
    shigure: ["hagumu", "himena"],
    himena: ["hagumu", "shigure"],
    nayuta: ["toka", "mikage"],
    mikage: ["nayuta", "mitama"],
    sakura: ["nemu", "ryo", "toka", "ui"],
    yuna: ["juri"],
    juri: ["yuna"],
}

const characterTitles = {
    yuma: "山猫冲击",
    kirika: "吸血鬼之牙",
    oriko: "神谕光线",
    ashley: "Ocean Tick Hurricane",
    riko: "美味猎手",
    rika: "闪耀光束",
    tsuruno: "炎扇斩舞",
    sana: "酷刑牢笼",
    iroha: "未来之路",
    yachiyo: "绝对之雨",
    felicia: "超级大大锤",
    toka: "新创世纪☆彡",
    alina: "九相",
    lena: "无尽海神",
    kaede: "大地审判",
    momoko: "宇宙之刃",
    asuka: "龙真螺旋咆击",
    yueye: "樱隐",
    yuexiao: "樱语",
    madoka: "魔法之雨",
    homura: "导弹集中轰炸",
    "homura2": "时间停止攻击",
    nanaka: "白椿",
    hazuki: "雷霆激流",
    karin: "幽紫灵火",
    nemu: "创造的孩子们",
    mami: "终幕射击",
    kyoko: "盟神抉枪",
    mabayu: "空洞人偶",
    ren: "灵魂救赎",
    "ulti_madoka": "已经没必要再绝望了！",
    sayaka: "无畏极强音",
    Kagome: "幻想之树",
    mifuyu: "侵袭妄想",
    meru: "漆黑的阿卡纳",
    kazumi: "外缘极限",
    kushu: "肃清天使",
    kokoro: "离散镭射",
    ayame: "未确认飞行火焰",
    hanna: "噩梦毒针",
    kuroe: "灾难盛宴",
    "dp_iroha": "沉默的魔女化身",
    kanae: "无思考",
    name: "无名少女",
    mitama: "绝对自坏演舞",
    ui: "希望之光",
    nagisa: "魔法肥皂泡",
    kanagi: "断罪的光芒",
    suzune: "燃椿之焰",
    dArc: "La Lumière",
    himika: "陨石拳",
    masara: "隐形暗杀",
    seika: "钻石飞溅",
    rera: "火焰之轮",
    mito: "绿叶如注",
    ryo: "绝对炎上观鸟炮!!",
    ai: "无名人工智能之谣",
    asumi: "绝望交响曲",
    "saint_mami": "神滨圣女之谣",
    "uwasa_tsuruno": "螯合游乐园之谣",
    "devil_homura": "棒针的连续穿刺",
    hinano: "狂怒原子",
    yuna: "雷霆埋葬",
    shigure: "极限爆破怨恨",
    hagumu: "转圈圈再见",
    shizuka: "巫流·祈祷通天之光",
    himena: "情绪摇滚爱★水妖",
    nayuta: "文化跃进的气流",
    mikage: "只有现在是坏孩子！",
    sakura: "万年樱之谣",
    juri: "无限灼热火焰龙击波",
}

const characterReplaces = {

};

export default characters;
export { character_translates, perfectPairs, characterTitles, characterReplaces };