import { lib, game, ui, get, ai, _status } from "../../noname.js";

const characters = {
    "yuma": {
        sex: "female",
        group: "yuan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["zhijian", "guzheng", "wangxi"],
        img: "extension/魔法纪录/image/yuma.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/yuma.mp3"],
        description: "山猫冲击"
    },
    "kirika": {
        sex: "female",
        group: "yuan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["xinshensu", "ganglie", "shebian"],
        img: "extension/魔法纪录/image/kirika.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/kirika.mp3"],
        description: "吸血鬼之牙"
    },
    "oriko": {
        sex: "female",
        group: "yuan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["oriko_yuzhi", "oriko_jiangsha", "weimu", "oriko_xianzhong"],
        img: "extension/魔法纪录/image/oriko.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/oriko.mp3"],
        description: "神谕光线",
        isZhugong: true
    },
    "ashley": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["ashley_yuanyu", "ashley_mengshu"],
        img: "extension/魔法纪录/image/ashley.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/ashley.mp3"],
        description: "Ocean Tick Hurricane"
    },
    "riko": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["dcduliang", "tunchu", "shuliang"],
        img: "extension/魔法纪录/image/riko.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/riko.mp3"],
        description: "美味猎手"
    },
    "rika": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["wanwei", "spyuejian", "reguose", "tianxiang"],
        img: "extension/魔法纪录/image/rika.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/rika.mp3"],
        description: "闪耀光束"
    },
    "tsuruno": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["tsuruno_qiangyun", "tsuruno_jizhi"],
        img: "extension/魔法纪录/image/tsuruno.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/tsuruno.mp3"],
        description: "炎扇斩舞"
    },
    "sana": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["sana_touming", "xinjushou", "xinjiewei"],
        img: "extension/魔法纪录/image/sana.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/sana.mp3"],
        description: "酷刑牢笼"
    },
    "iroha": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["olhaoshi", "oldimeng", "dckrmingshi", "yuanjiu"],
        img: "extension/魔法纪录/image/iroha.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/iroha.mp3"],
        description: "未来之路",
        isZhugong: true
    },
    "yachiyo": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["rexingshang", "fangzhu", "yachiyo_gujun"],
        img: "extension/魔法纪录/image/yachiyo.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/yachiyo.mp3"],
        description: "绝对之雨",
        isZhugong: true
    },
    "felicia": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["repojun", "reyicong"],
        img: "extension/魔法纪录/image/felicia.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/felicia.mp3"],
        description: "超级大大锤"
    },
    "toka": {
        sex: "female",
        group: "ma",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["xinleiji", "xinguidao", "magius_jiefang"],
        img: "extension/魔法纪录/image/toka.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/toka.mp3"],
        description: "新创世纪",
        isZhugong: true
    },
    "alina": {
        sex: "female",
        group: "ma",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["moying", "juanhui", "reshejian"],
        img: "extension/魔法纪录/image/alina.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/alina.mp3"],
        description: "九相"
    },
    "lena": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["rehuashen", "rexinsheng"],
        img: "extension/魔法纪录/image/lena.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/lena.mp3"],
        description: "无尽海神"
    },
    "kaede": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["kaede_manmiao", "jijiu", "xinbuyi", "dczhuiyi"],
        img: "extension/魔法纪录/image/kaede.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/kaede.mp3"],
        description: "大地审判",
        doubleGroup: ["huan", "ma"],
    },
    "momoko": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["qiangxix", "buqu"],
        img: "extension/魔法纪录/image/momoko.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/momoko.mp3"],
        description: "宇宙之刃"
    },
    "asuka": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["kurou", "asuka_longzhen"],
        img: "extension/魔法纪录/image/asuka.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/asuka.mp3"],
        description: "龙真螺旋咆击"
    },
    "yueye": {
        sex: "female",
        group: "ma",
        hp: 5,
        maxHp: 5,
        hujia: 0,
        skills: ["olshuangxiong"],
        img: "extension/魔法纪录/image/yueye.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/yueye.mp3"],
        description: "樱隐"
    },
    "yuexiao": {
        sex: "female",
        group: "ma",
        hp: 5,
        maxHp: 5,
        hujia: 0,
        skills: ["olfuhun"],
        img: "extension/魔法纪录/image/yuexiao.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/yuexiao.mp3"],
        description: "樱语"
    },
    "madoka": {
        sex: "female",
        group: "yuan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["madoka_liegong", "madoka_yingbian", "xieli"],
        img: "extension/魔法纪录/image/madoka.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/madoka.mp3"],
        description: "魔法之雨",
        isZhugong: true
    },
    "homura": {
        sex: "female",
        group: "yuan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["reguanxing", "homura_juwu", "homura_shiting"],
        img: "extension/魔法纪录/image/homura.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/homura.mp3"],
        description: "导弹集中轰炸"
    },
    "homura2": {
        sex: "female",
        group: "yuan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["homura2_jihuo", "yiji", "huoji"],
        img: "extension/魔法纪录/image/homura2.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/homura2.mp3"],
        description: "时间停止攻击"
    },
    "nanaka": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["nanaka_huaxin", "rejizhi"],
        img: "extension/魔法纪录/image/nanaka.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/nanaka.mp3"],
        description: "白椿"
    },
    "hazuki": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["huituo", "hazuki_mingjian"],
        img: "extension/魔法纪录/image/hazuki.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/hazuki.mp3"],
        description: "雷霆激流"
    },
    "karin": {
        sex: "female",
        group: "ma",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["daoshu", "weicheng"],
        img: "extension/魔法纪录/image/karin.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/karin.mp3"],
        description: "幽紫灵火",
        doubleGroup: ["huan", "ma"],
    },
    "nemu": {
        sex: "female",
        group: "ma",
        hp: 5,
        maxHp: 5,
        hujia: 0,
        skills: ["nemu_zhiyao", "nemu_sanyao", "nemu_tiruo"],
        img: "extension/魔法纪录/image/nemu.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/nemu.mp3"],
        description: "创造的孩子们"
    },
    "mami": {
        sex: "female",
        group: "yuan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["reyingzi", "guose", "sbluanji", "mami_qiaobian"],
        img: "extension/魔法纪录/image/mami.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/mami.mp3"],
        description: "终幕射击"
    },
    "kyoko": {
        sex: "female",
        group: "yuan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["oltuntian", "jixi", "reguhuo"],
        img: "extension/魔法纪录/image/kyoko.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/kyoko.mp3"],
        description: "盟神决枪"
    },
    "mabayu": {
        sex: "female",
        group: "yuan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["nzry_chenglve", "nzry_cunmu", "nzry_shicai", "mabayu_jingxiang"],
        img: "extension/魔法纪录/image/mabayu.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/mabayu.mp3"],
        description: "空洞人偶",
        isZhugong: true
    },
    "ren": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["xinwuyan", "olbeige", "duanchang"],
        img: "extension/魔法纪录/image/ren.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/ren.mp3"],
        description: "灵魂救赎"
    },
    "ulti_madoka": {
        sex: "female",
        group: "yuan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["twshelie", "twgongxin", "sbliegong", "xieli"],
        img: "extension/魔法纪录/image/ulti_madoka.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/ulti_madoka.mp3"],
        description: "再也没有必要绝望了！",
        isZhugong: true
    },
    "sayaka": {
        sex: "female",
        group: "yuan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["xinkuanggu", "gzyinghun", "sayaka_qiangyin"],
        img: "extension/魔法纪录/image/sayaka.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/sayaka.mp3"],
        description: "无畏极强音"
    },
    "Kagome": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["hschenzhi", "hsdianmo", "hszaibi", "reqingguo"],
        img: "extension/魔法纪录/image/Kagome.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/Kagome.mp3"]
    },
    "mifuyu": {
        sex: "female",
        group: "ma",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["dcwumei", "dczhanmeng"],
        img: "extension/魔法纪录/image/mifuyu.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/mifuyu.mp3"],
        doubleGroup: ["huan", "ma"],
    },
    "meru": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["zhiming", "twxingbu"],
        img: "extension/魔法纪录/image/meru.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/meru.mp3"]
    },
    "kazumi": {
        sex: "female",
        group: "wan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["qixing", "kuangfeng", "dawu", "kazumi_xingyun"],
        img: "extension/魔法纪录/image/kazumi.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/kazumi.mp3"],
        isZhugong: true
    },
    "kushu": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["jiushi", "keji", "refankui"],
        img: "extension/魔法纪录/image/kushu.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/kushu.mp3"],
        description: "肃清天使"
    },
    "kokoro": {
        sex: "female",
        group: "huan",
        hp: 5,
        maxHp: 5,
        hujia: 0,
        skills: ["jieyue", "yizhong"],
        img: "extension/魔法纪录/image/kokoro.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/kokoro.mp3"],
        description: "离散镭射"
    },
    "ayame": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["tianyi", "hanzhan"],
        img: "extension/魔法纪录/image/ayame.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/ayame.mp3"],
        description: "未确认飞行火焰"
    },
    "hanna": {
        sex: "female",
        group: "ma",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["xinjuece", "dcmieji", "dcfencheng", "reluanwu"],
        img: "extension/魔法纪录/image/hanna.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/hanna.mp3"],
        description: "噩梦毒针"
    },
    "kuroe": {
        sex: "female",
        group: "ma",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["qingbei", "dcsuishi"],
        img: "extension/魔法纪录/image/kuroe.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/kuroe.mp3"],
        description: "灾难盛宴",
        doubleGroup: ["huan", "ma"],
    },
    "anime_iroha": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["ani_lieying", "yuanjiu", "test_skill"],
        img: "extension/魔法纪录/image/anime_iroha.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/anime_iroha.mp3"],
        isZhugong: true,
        isAiForbidden: true
    },
    "kanae": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["kaikang"],
        img: "extension/魔法纪录/image/kanae.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/kanae.mp3"]
    },
    "name": {
        sex: "female",
        group: "yuan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["name_dengtai"],
        img: "extension/魔法纪录/image/name.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/name.mp3"]
    },
    "mitama": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["gongxiu", "jinghe", "ns_chuanshu"],
        img: "extension/魔法纪录/image/mitama.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/mitama.mp3"],
        doubleGroup: ["huan", "ma"],
    },
    "ui": {
        sex: "female",
        group: "ma",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["ui_jinghua", "ui_wangyou", "ui_leshan", "dckrmingshi"],
        img: "extension/魔法纪录/image/ui.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/ui.mp3"],
        doubleGroup: ["huan", "ma"],
    },
    "nagisa": {
        sex: "female",
        group: "yuan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["tiandu", "ollianhuan", "olniepan", "olsbqiwu"],
        img: "extension/魔法纪录/image/nagisa.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/nagisa.mp3"]
    },
    "kanagi": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["reshuishi", "kanagi_duxin", "kanagi_nvpu", "kanagi_dongyou"],
        img: "extension/魔法纪录/image/kanagi.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/kanagi.mp3"],
        isZhugong: true
    },
    "suzune": {
        sex: "female",
        group: "wan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["retuogu", "shanzhuan"],
        img: "extension/魔法纪录/image/suzune.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/suzune.mp3"]
    },
    "dArc": {
        sex: "female",
        group: "wan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["dArc_congjun", "nanaka_huaxin", "gongji"],
        img: "extension/魔法纪录/image/dArc.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/dArc.mp3"]
    },
    "himika": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["dclihuo", "olchunlao"],
        img: "extension/魔法纪录/image/himika.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/himika.mp3"],
        description: "陨石拳"
    },
    "masara": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["rebiyue", "masara_cisha", "qiluan"],
        img: "extension/魔法纪录/image/masara.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/masara.mp3"],
        description: "隐形刺杀"
    },
    "seika": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["dcxiongyi"],
        img: "extension/魔法纪录/image/seika.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/seika.mp3"],
        description: "钻石飞溅"
    },
    "rera": {
        sex: "female",
        group: "huan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["xinfu_jijie", "rera_nuanxin"],
        img: "extension/魔法纪录/image/rera.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/rera.mp3"],
        description: "火焰之环"
    },
    "mito": {
        sex: "female",
        group: "huan",
        hp: 5,
        maxHp: 5,
        hujia: 0,
        skills: ["dcshuangren", "hanzhan"],
        img: "extension/魔法纪录/image/mito.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/mito.mp3"],
        description: "绿叶如注"
    },
    "ryo": {
        sex: "female",
        group: "ma",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["ryo_yaozuo", "dcsbzhuanwen"],
        img: "extension/魔法纪录/image/ryo.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/ryo.mp3"]
    },
    "ai": {
        sex: "female",
        group: "ma",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["xingtu", "juezhi", "ai_shuxin"],
        img: "extension/魔法纪录/image/ai.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/ai.mp3"],
        description: "无名人工智能之谣",
    },
    "asumi": {
        sex: "female",
        group: "yuan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["asumi_zhuilie", "asumi_yinhu"],
        img: "extension/魔法纪录/image/asumi.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/asumi.mp3"],
        description: "绝望交响曲",
    },
    "saint_mami": {
        sex: "female",
        group: "ma",
        hp: 5,
        maxHp: 5,
        hujia: 0,
        skills: ["reyingzi", "reluanji", "starxiaoyan", "starjiaowang"],
        img: "extension/魔法纪录/image/saint_mami.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/saint_mami.mp3"],
    },
    "uwasa_tsuruno": {
        sex: "female",
        group: "ma",
        hp: 5,
        maxHp: 5,
        hujia: 0,
        skills: ["tsuruno_qiangyun", "drlt_jueyan", "tsuruno_tuanluan"],
        img: "extension/魔法纪录/image/uwasa_tsuruno.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/uwasa_tsuruno.mp3"],
    },
    "devil_homura": {
        sex: "female",
        group: "yuan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["dcgeyuan", "dcgusuan", "dcjieshu", "bazhen"],
        img: "extension/魔法纪录/image/devil_homura.jpg",
    },
    "hinano": {
        sex: "female",
        group: "huan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["hinano_huawu", "hinano_duji", "hinano_shiyao", "hinano_baoming"],
        img: "extension/魔法纪录/image/hinano.png",
    },
    "yuna": {
        isZhugong: true,
        sex: "female",
        group: "wan",
        hp: 3,
        maxHp: 3,
        hujia: 0,
        skills: ["yuna_chouhai", "yuna_xuehen", "yuna_liuli", "yuna_xuemeng"],
        img: "extension/魔法纪录/image/yuna.png",
    },
    "shigure": {
        sex: "female",
        group: "ma",
        hp: 5,
        maxHp: 5,
        hujia: 0,
        skills: ["olkanpo", "ollongdan"],
        img: "extension/魔法纪录/image/shigure.png",
    },
    "hagumu": {
        sex: "female",
        group: "ma",
        hp: 5,
        maxHp: 5,
        hujia: 0,
        skills: ["new_rewusheng", "oltiaoxin"],
        img: "extension/魔法纪录/image/hagumu.png",
    },
    "shizuka": {
        sex: "female",
        group: "wan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["shizuka_xueji", "komari_xueshang"],
        img: "extension/魔法纪录/image/shizuka.png",
    },
    "himena": {
        isZhugong: true,
        sex: "female",
        group: "ma",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["rejijun", "refangtong", "magius_zhishang"],
        img: "extension/魔法纪录/image/himena.png",
    }
}

const character_translates = {
    "ulti_madoka_prefix": "神",
    "魔法纪录": "魔法纪录",
    yuma: "千岁由麻",
    kirika: "吴纪里香",
    oriko: "美国织莉子",
    ashley: "阿什莉·泰勒",
    riko: "千秋理子",
    rika: "绫野梨花",
    tsuruno: "由比鹤乃",
    sana: "二叶莎奈",
    iroha: "环彩羽",
    yachiyo: "七海八千代",
    felicia: "深月菲莉西亚",
    toka: "里见灯花",
    alina: "阿莉娜·格雷",
    lena: "水波玲奈",
    kaede: "秋野枫",
    momoko: "十咎桃子",
    asuka: "龙城明日香",
    yueye: "天音月夜",
    yuexiao: "天音月咲",
    madoka: "鹿目圆",
    homura: "晓美焰",
    "homura2": "麻花焰",
    nanaka: "常盘七香",
    hazuki: "游佐叶月",
    karin: "御园花凛",
    nemu: "柊音梦",
    mami: "巴麻美",
    kyoko: "佐仓杏子",
    mabayu: "爱生眩",
    ren: "五十铃怜",
    "ulti_madoka": "神鹿目圆",
    sayaka: "美树沙耶香",
    Kagome: "佐鸟笼目",
    mifuyu: "梓美冬",
    meru: "安名梅露",
    kazumi: "和美",
    kushu: "入名库什",
    kokoro: "粟根心",
    ayame: "三栗菖蒲",
    hanna: "更纱帆奈",
    kuroe: "黑江",
    "anime_iroha": "DP环彩羽",
    "anime_iroha_prefix": "DP",
    kanae: "雪野加奈惠",
    name: "小名",
    mitama: "八云御魂",
    ui: "环忧",
    nagisa: "百江渚",
    kanagi: "和泉十七夜",
    suzune: "天乃铃音",
    dArc: "贞德",
    himika: "真尾日美香",
    masara: "加贺见真良",
    seika: "桑水清佳",
    rera: "伊吹丽良",
    mito: "相野未都",
    ryo: "观鸟令",
    ai: "爱酱",
    asumi: "神名浅海",
    "saint_mami": "圣巴麻美",
    "saint_mami_prefix": "圣",
    "uwasa_tsuruno": "谣由比鹤乃",
    "uwasa_tsuruno_prefix": "谣",
    "devil_homura": "魔晓美焰",
    "devil_homura_prefix": "魔",
    hinano: "都雏乃",
    yuna: "红晴结菜",
    shigure: "宫尾时雨",
    hagumu: "安积育梦",
    shizuka: "时女静香",
    himena: "蓝家姬奈",
}

const perfectPairs = {
    oriko: ["kirika"],
    kirika: ["oriko"],
    madoka: ["homura", "mami", "sayaka", "homura2", "ulti_madoka", "devil_homura"],
    "ulti_madoka": ["sayaka", "homura", "madoka", "devil_homura"],
    homura: ["madoka", "homura2", "ulti_madoka", "kyoko", "mabayu", "devil_homura"],
    "homura2": ["madoka", "mami", "sayaka", "homura", "devil_homura"],
    "devil_homura": ["homura", "homura2", "ulti_madoka", "madoka"],
    mami: ["kyoko", "mabayu", "homura2", "madoka", "sayaka", "nagisa"],
    kyoko: ["mami", "homura", "homura2", "sayaka", "yuma"],
    sayaka: ["madoka", "kyoko", "homura2", "mami"],
    yuma: ["kyoko"],
    mabayu: ["mami", "homura", "homura2"],
    iroha: ["yachiyo", "felicia", "sana", "kuroe", "ui"],
    yachiyo: ["iroha", "tsuruno", "momoko", "mifuyu", "meru", "kanae"],
    felicia: ["iroha", "tsuruno"],
    tsuruno: ["felicia", "yachiyo"],
    sana: ["iroha"],
    momoko: ["yachiyo", "kaede", "lena", "mitama"],
    lena: ["momoko", "kaede"],
    kaede: ["momoko", "lena"],
    toka: ["alina", "nemu", "ui"],
    alina: ["toka", "nemu", "karin"],
    nemu: ["alina", "toka", "ui"],
    karin: ["alina"],
    nanaka: ["hazuki"],
    hazuki: ["nanaka"],
    yueye: ["yuexiao", "mifuyu"],
    yuexiao: ["yueye"],
    ashley: ["riko"],
    riko: ["ashley"],
    rika: ["ren"],
    ren: ["rika"],
    mifuyu: ["yachiyo", "toka", "yueye"],
    meru: ["yachiyo"],
    kuroe: ["iroha"],
    kanae: ["yachiyo"],
    mitama: ["momoko"],
    nagisa: ["mami"],
    ui: ["toka", "nemu", "iroha"],
    kokoro: ["masara"],
    masara: ["kokoro"],
    mito: ["seika", "rera"],
    seika: ["mito", "rera"],
    rera: ["seika", "mito"],
    hagumu: ["shigure", "himena"],
    shigure: ["hagumu", "himena"],
    himena: ["hagumu", "shigure"],
}

export default characters;
export { character_translates, perfectPairs };