import { lib, game, ui, get, ai, _status } from "../../noname.js";

const characters = {
    yuma: ["female", "yuan", 3, ["zhijian", "guzheng", "wangxi"], ["des:山猫冲击", "ext:魔法纪录/image/yuma.jpg", "die:ext:魔法纪录/audio/die/yuma.mp3"]],
    kirika: ["female", "yuan", 4, ["xinshensu", "ganglie", "shebian"], ["des:吸血鬼之牙", "ext:魔法纪录/image/kirika.jpg", "die:ext:魔法纪录/audio/die/kirika.mp3"]],
    oriko: ["female", "yuan", 3, ["oriko_yuzhi", "oriko_jiangsha", "weimu", "oriko_xianzhong"], ["zhu", "des:神谕光线", "ext:魔法纪录/image/oriko.jpg", "die:ext:魔法纪录/audio/die/oriko.mp3"]],
    ashley: ["female", "huan", 4, ["ashley_yuanyu", "ashley_mengshu"], ["des:Ocean Tick Hurricane", "ext:魔法纪录/image/ashley.jpg", "die:ext:魔法纪录/audio/die/ashley.mp3"]],
    riko: ["female", "huan", 3, ["dcduliang", "dctunchu", "dcshuliang"], ["des:美味猎手", "ext:魔法纪录/image/riko.jpg", "die:ext:魔法纪录/audio/die/riko.mp3"]],
    rika: ["female", "huan", 3, ["wanwei", "spyuejian", "reguose", "tianxiang"], ["des:闪耀光束", "ext:魔法纪录/image/rika.jpg", "die:ext:魔法纪录/audio/die/rika.mp3"]],
    tsuruno: ["female", "huan", 4, ["tsuruno_qiangyun", "jiang", "lianying", "hunzi"], ["des:炎扇斩舞", "ext:魔法纪录/image/tsuruno.jpg", "die:ext:魔法纪录/audio/die/tsuruno.mp3"]],
    sana: ["female", "huan", 4, ["sana_touming", "xinjushou", "xinjiewei"], ["des:酷刑牢笼", "ext:魔法纪录/image/sana.jpg", "die:ext:魔法纪录/audio/die/sana.mp3"]],
    iroha: ["female", "huan", 3, ["olhaoshi", "oldimeng", "dckrmingshi", "yuanjiu"], ["zhu", "des:未来之路", "ext:魔法纪录/image/iroha.jpg", "die:ext:魔法纪录/audio/die/iroha.mp3"]],
    yachiyo: ["female", "huan", 4, ["xingshang", "fangzhu", "yachiyo_gujun"], ["zhu", "des:绝对之雨", "ext:魔法纪录/image/yachiyo.jpg", "die:ext:魔法纪录/audio/die/yachiyo.mp3"]],
    felicia: ["female", "huan", 4, ["repojun", "reyicong"], ["des:超级大大锤", "ext:魔法纪录/image/felicia.jpg", "die:ext:魔法纪录/audio/die/felicia.mp3"]],
    toka: ["female", "ma", 3, ["xinleiji", "xinguidao", "tianjie", "magius_jiefang"], ["zhu", "des:新创世纪", "ext:魔法纪录/image/toka.jpg", "die:ext:魔法纪录/audio/die/toka.mp3"]],
    alina: ["female", "ma", 3, ["moying", "juanhui", "reshejian"], ["des:九相", "ext:魔法纪录/image/alina.jpg", "die:ext:魔法纪录/audio/die/alina.mp3"]],
    lena: ["female", "huan", 3, ["rehuashen", "rexinsheng"], ["des:无尽海神", "ext:魔法纪录/image/lena.jpg", "die:ext:魔法纪录/audio/die/lena.mp3"]],
    kaede: ["female", "huan", 3, ["kaede_manmiao", "jijiu", "xinbuyi", "dczhuiyi"], ["doublegroup:huan:ma", "des:大地审判", "ext:魔法纪录/image/kaede.jpg", "die:ext:魔法纪录/audio/die/kaede.mp3"]],
    momoko: ["female", "huan", 4, ["qiangxix", "buqu"], ["des:宇宙之刃", "ext:魔法纪录/image/momoko.jpg", "die:ext:魔法纪录/audio/die/momoko.mp3"]],
    asuka: ["female", "huan", 4, ["kurou", "asuka_longzhen"], ["des:龙真螺旋咆击", "ext:魔法纪录/image/asuka.jpg", "die:ext:魔法纪录/audio/die/asuka.mp3"]],
    yueye: ["female", "ma", 5, ["olshuangxiong"], ["des:樱隐", "ext:魔法纪录/image/yueye.jpg", "die:ext:魔法纪录/audio/die/yueye.mp3"]],
    yuexiao: ["female", "ma", 5, ["olfuhun"], ["des:樱语", "ext:魔法纪录/image/yuexiao.jpg", "die:ext:魔法纪录/audio/die/yuexiao.mp3"]],
    madoka: ["female", "yuan", 3, ["madoka_liegong", "madoka_yingbian", "xieli"], ["zhu", "des:魔法之雨", "ext:魔法纪录/image/madoka.jpg", "die:ext:魔法纪录/audio/die/madoka.mp3"]],
    homura: ["female", "yuan", 3, ["reguanxing", "luoshen", "homura_shiting"], ["des:导弹集中轰炸", "ext:魔法纪录/image/homura.jpg", "die:ext:魔法纪录/audio/die/homura.mp3"]],
    "homura2": ["female", "yuan", 3, ["homura2_jihuo", "yiji", "huoji"], ["des:时间停止攻击", "ext:魔法纪录/image/homura2.jpg", "die:ext:魔法纪录/audio/die/homura2.mp3"]],
    nanaka: ["female", "huan", 3, ["nanaka_huaxin", "jizhi"], ["des:白椿", "ext:魔法纪录/image/nanaka.jpg", "die:ext:魔法纪录/audio/die/nanaka.mp3"]],
    hazuki: ["female", "huan", 3, ["huituo", "hazuki_mingjian"], ["des:雷霆激流", "ext:魔法纪录/image/hazuki.jpg", "die:ext:魔法纪录/audio/die/hazuki.mp3"]],
    karin: ["female", "ma", 3, ["daoshu", "weicheng"], ["des:幽紫灵火", "ext:魔法纪录/image/karin.jpg", "doublegroup:huan:ma", "die:ext:魔法纪录/audio/die/karin.mp3"]],
    nemu: ["female", "ma", 5, ["nemu_zhiyao", "nemu_sanyao", "nemu_tiruo"], ["des:创造的孩子们", "ext:魔法纪录/image/nemu.jpg", "die:ext:魔法纪录/audio/die/nemu.mp3"]],
    mami: ["female", "yuan", 4, ["guose", "reyingzi", "sbluanji", "qiaobian"], ["des:终幕射击", "ext:魔法纪录/image/mami.jpg", "die:ext:魔法纪录/audio/die/mami.mp3"]],
    kyoko: ["female", "yuan", 4, ["oltuntian", "reguhuo", "jixi"], ["des:盟神决枪", "ext:魔法纪录/image/kyoko.jpg", "die:ext:魔法纪录/audio/die/kyoko.mp3"]],
    mabayu: ["female", "yuan", 3, ["nzry_chenglve", "nzry_cunmu", "nzry_shicai", "mabayu_jingxiang"], ["zhu", "des:空洞人偶", "ext:魔法纪录/image/mabayu.jpg", "die:ext:魔法纪录/audio/die/mabayu.mp3"]],
    ren: ["female", "huan", 3, ["xinwuyan", "olbeige", "duanchang"], ["des:灵魂救赎", "ext:魔法纪录/image/ren.jpg", "die:ext:魔法纪录/audio/die/ren.mp3"]],
    "ulti_madoka": ["female", "yuan", 4, ["twshelie", "twgongxin", "sbliegong", "xieli"], ["zhu", "des:再也没有必要绝望了！", "ext:魔法纪录/image/ulti_madoka.jpg", "die:ext:魔法纪录/audio/die/ulti_madoka.mp3"]],
    sayaka: ["female", "yuan", 4, ["xinkuanggu", "gzyinghun", "sayaka_qiangyin"], ["des:无畏极强音", "ext:魔法纪录/image/sayaka.jpg", "die:ext:魔法纪录/audio/die/sayaka.mp3"]],
    Kagome: ["female", "huan", 3, ["hschenzhi", "hsdianmo", "hszaibi", "reqingguo"], ["ext:魔法纪录/image/Kagome.jpg", "die:ext:魔法纪录/audio/die/Kagome.mp3"]],
    mifuyu: ["female", "ma", 3, ["dcwumei", "dczhanmeng"], ["doublegroup:huan:ma", "ext:魔法纪录/image/mifuyu.jpg", "die:ext:魔法纪录/audio/die/mifuyu.mp3"]],
    meru: ["female", "huan", 3, ["zhiming", "twxingbu"], ["des:", "ext:魔法纪录/image/meru.jpg", "die:ext:魔法纪录/audio/die/meru.mp3"]],
    kazumi: ["female", "wan", 3, ["qixing", "kuangfeng", "dawu", "kazumi_xingyun"], ["zhu", "ext:魔法纪录/image/kazumi.jpg", "die:ext:魔法纪录/audio/die/kazumi.mp3"]],
    kushu: ["female", "huan", 4, ["jiushi", "keji", "refankui"], ["des:肃清天使", "ext:魔法纪录/image/kushu.jpg", "die:ext:魔法纪录/audio/die/kushu.mp3"]],
    kokoro: ["female", "huan", 5, ["jieyue", "yizhong"], ["des:离散镭射", "ext:魔法纪录/image/kokoro.jpg", "die:ext:魔法纪录/audio/die/kokoro.mp3"]],
    ayame: ["female", "huan", 4, ["tianyi", "hanzhan"], ["des:未确认飞行火焰", "ext:魔法纪录/image/ayame.jpg", "die:ext:魔法纪录/audio/die/ayame.mp3"]],
    hanna: ["female", "ma", 3, ["reluanwu", "xinjuece", "dcmieji", "dcfencheng"], ["des:噩梦毒针", "ext:魔法纪录/image/hanna.jpg", "die:ext:魔法纪录/audio/die/hanna.mp3"]],
    kuroe: ["female", "ma", 4, ["qingbei", "dcsuishi"], ["doublegroup:huan:ma", "des:灾难盛宴", "ext:魔法纪录/image/kuroe.jpg", "die:ext:魔法纪录/audio/die/kuroe.mp3"]],
    "anime_iroha": ["female", "huan", 3, ["ani_lieying", "yuanjiu", "test_skill"], ["forbidai", "zhu", "ext:魔法纪录/image/anime_iroha.jpg", "die:ext:魔法纪录/audio/die/anime_iroha.mp3"]],
    kanae: ["female", "huan", 4, ["kaikang"], ["ext:魔法纪录/image/kanae.jpg", "die:ext:魔法纪录/audio/die/kanae.mp3"]],
    name: ["female", "yuan", 3, ["dcchushan"], ["ext:魔法纪录/image/name.jpg", "die:ext:魔法纪录/audio/die/name.mp3"]],
    mitama: ["female", "huan", 3, ["gongxiu", "jinghe", "ns_chuanshu"], ["doublegroup:huan:ma", "ext:魔法纪录/image/mitama.jpg", "die:ext:魔法纪录/audio/die/mitama.mp3"]],
    ui: ["female", "ma", 3, ["ui_jinghua", "ui_wangyou", "ui_leshan", "dckrmingshi"], ["doublegroup:huan:ma", "ext:魔法纪录/image/ui.jpg", "die:ext:魔法纪录/audio/die/ui.mp3"]],
    nagisa: ["female", "yuan", 3, ["tiandu", "ollianhuan", "olniepan", "olsbqiwu"], ["ext:魔法纪录/image/nagisa.jpg", "die:ext:魔法纪录/audio/die/nagisa.mp3"]],
    kanagi: ["female", "huan", 4, ["reshuishi", "kanagi_duxin", "kanagi_nvpu", "kanagi_dongyou"], ["zhu", "ext:魔法纪录/image/kanagi.jpg", "die:ext:魔法纪录/audio/die/kanagi.mp3"]],
    suzune: ["female", "wan", 4, ["retuogu", "shanzhuan"], ["ext:魔法纪录/image/suzune.jpg", "die:ext:魔法纪录/audio/die/suzune.mp3"]],
    dArc: ["female", "wan", 4, ["dArc_congjun", "nanaka_huaxin", "gongji"], ["ext:魔法纪录/image/dArc.jpg", "die:ext:魔法纪录/audio/die/dArc.mp3"]],
    himika: ["female", "huan", 4, ["dclihuo", "olchunlao"], ["des:陨石拳", "ext:魔法纪录/image/himika.jpg", "die:ext:魔法纪录/audio/die/himika.mp3"]],
    masara: ["female", "huan", 4, ["rebiyue", "zhendu", "qiluan"], ["des:隐形刺杀", "ext:魔法纪录/image/masara.jpg", "die:ext:魔法纪录/audio/die/masara.mp3"]],
    seika: ["female", "huan", 4, ["dcxiongyi"], ["des:钻石飞溅", "ext:魔法纪录/image/seika.jpg", "die:ext:魔法纪录/audio/die/seika.mp3"]],
    rera: ["female", "huan", 4, ["xinfu_jijie", "rera_nuanxin"], ["des:火焰之环", "ext:魔法纪录/image/rera.jpg", "die:ext:魔法纪录/audio/die/rera.mp3"]],
    mito: ["female", "huan", 5, ["dcshuangren", "hanzhan"], ["des:绿叶如注", "ext:魔法纪录/image/mito.jpg", "die:ext:魔法纪录/audio/die/mito.mp3"]],
    ryo: ["female", "ma", 4, ["dcsbyaozuo", "dcsbzhuanwen"], ["ext:魔法纪录/image/ryo.jpg", "die:ext:魔法纪录/audio/die/ryo.mp3"]],
    ai: ["female", "ma", 3, ["xingtu", "juezhi", "ai_shuxin"], ["ext:魔法纪录/image/ai.jpg", "die:ext:魔法纪录/audio/die/ai.mp3"]],
    asumi: ["female", "yuan", 4, ["spzhuilie", "zhaxiang"], ["ext:魔法纪录/image/asumi.jpg", "die:ext:魔法纪录/audio/die/asumi.mp3"]],
    "saint_mami": {
        sex: "female",
        group: "ma",
        hp: 5,
        maxHp: 5,
        hujia: 0,
        skills: ["reyingzi", "reluanji", "starxiaoyan", "starjiaowang"],
        img: "extension/魔法纪录/image/saint_mami.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/saint_mami.mp3"],
    },
    "uwasa_tsuruno": {
        sex: "female",
        group: "ma",
        hp: 5,
        maxHp: 5,
        hujia: 0,
        skills: ["tsuruno_qiangyun", "drlt_jueyan", "tsuruno_tuanluan", "relianying"],
        img: "extension/魔法纪录/image/uwasa_tsuruno.jpg",
        dieAudios: ["ext:魔法纪录/audio/die/uwasa_tsuruno.mp3"],
    },
    "devil_homura": {
        sex: "female",
        group: "yuan",
        hp: 4,
        maxHp: 4,
        hujia: 0,
        skills: ["dcgeyuan", "dcgusuan", "dcjieshu", "bazhen"],
        img: "extension/魔法纪录/image/devil_homura.jpg",
    },
}

const character_translates = {
    "ulti_madoka_prefix": "神",
    "魔法纪录": "魔法纪录",
    yuma: "千岁由麻",
    kirika: "吴纪里香",
    oriko: "美国织莉子",
    ashley: "阿什莉·泰勒",
    riko: "千秋理子",
    rika: "绫野梨花",
    tsuruno: "由比鹤乃",
    sana: "二叶莎奈",
    iroha: "环彩羽",
    yachiyo: "七海八千代",
    felicia: "深月菲莉西亚",
    toka: "里见灯花",
    alina: "阿莉娜·格雷",
    lena: "水波玲奈",
    kaede: "秋野枫",
    momoko: "十咎桃子",
    asuka: "龙城明日香",
    yueye: "天音月夜",
    yuexiao: "天音月咲",
    madoka: "鹿目圆",
    homura: "晓美焰",
    "homura2": "麻花焰",
    nanaka: "常盘七香",
    hazuki: "游佐叶月",
    karin: "御园花凛",
    nemu: "柊音梦",
    mami: "巴麻美",
    kyoko: "佐仓杏子",
    mabayu: "爱生眩",
    ren: "五十铃怜",
    "ulti_madoka": "神鹿目圆",
    sayaka: "美树沙耶香",
    Kagome: "佐鸟笼目",
    mifuyu: "梓美冬",
    meru: "安名梅露",
    kazumi: "和美",
    kushu: "入名库什",
    kokoro: "粟根心",
    ayame: "三栗菖蒲",
    hanna: "更纱帆奈",
    kuroe: "黑江",
    "anime_iroha": "DP环彩羽",
    "anime_iroha_prefix": "DP",
    kanae: "雪野加奈惠",
    name: "小名",
    mitama: "八云御魂",
    ui: "环忧",
    nagisa: "百江渚",
    kanagi: "和泉十七夜",
    suzune: "天乃铃音",
    dArc: "贞德",
    himika: "真尾日美香",
    masara: "加贺见真良",
    seika: "桑水清佳",
    rera: "伊吹丽良",
    mito: "相野未都",
    ryo: "观鸟令",
    ai: "爱酱",
    asumi: "神名浅海",
    "saint_mami": "圣麻美",
    "saint_mami_prefix": "圣",
    "uwasa_tsuruno": "谣鹤乃",
    "uwasa_tsuruno_prefix": "谣",
    "devil_homura": "魔晓美焰",
    "devil_homura_prefix": "魔",
}

const perfectPairs = {
    oriko: ["kirika"],
    kirika: ["oriko"],
    madoka: ["homura", "mami", "sayaka", "homura2", "ulti_madoka", "devil_homura"],
    "ulti_madoka": ["sayaka", "homura", "madoka", "devil_homura"],
    homura: ["madoka", "homura2", "ulti_madoka", "kyoko", "mabayu", "devil_homura"],
    "homura2": ["madoka", "mami", "sayaka", "homura", "devil_homura"],
    "devil_homura": ["homura", "homura2", "ulti_madoka", "madoka"],
    mami: ["kyoko", "mabayu", "homura2", "madoka", "sayaka", "nagisa"],
    kyoko: ["mami", "homura", "homura2", "sayaka", "yuma"],
    sayaka: ["madoka", "kyoko", "homura2", "mami"],
    yuma: ["kyoko"],
    mabayu: ["mami", "homura", "homura2"],
    iroha: ["yachiyo", "felicia", "sana", "kuroe", "ui"],
    yachiyo: ["iroha", "tsuruno", "momoko", "mifuyu", "meru", "kanae"],
    felicia: ["iroha", "tsuruno"],
    tsuruno: ["felicia", "yachiyo"],
    sana: ["iroha"],
    momoko: ["yachiyo", "kaede", "lena", "mitama"],
    lena: ["momoko", "kaede"],
    kaede: ["momoko", "lena"],
    toka: ["alina", "nemu", "ui"],
    alina: ["toka", "nemu", "karin"],
    nemu: ["alina", "toka", "ui"],
    karin: ["alina"],
    nanaka: ["hazuki"],
    hazuki: ["nanaka"],
    yueye: ["yuexiao", "mifuyu"],
    yuexiao: ["yueye"],
    ashley: ["riko"],
    riko: ["ashley"],
    rika: ["ren"],
    ren: ["rika"],
    mifuyu: ["yachiyo", "toka", "yueye"],
    meru: ["yachiyo"],
    kuroe: ["iroha"],
    kanae: ["yachiyo"],
    mitama: ["momoko"],
    nagisa: ["mami"],
    ui: ["toka", "nemu", "iroha"],
    kokoro: ["masara"],
    masara: ["kokoro"],
    mito: ["seika", "rera"],
    seika: ["mito", "rera"],
    rera: ["seika", "mito"],
}

export default characters;
export { character_translates, perfectPairs };